### ISSUE TITLE
Error in getOctD(x, offset, len) : invalid octal digit

### ISSUE THREAD

**Issue by pikapika505** [PeeperLab/XenofilteR#12]
Trying to install this package

`R CMD INSTALL XenofilteR_1.6.tar.gz`

I get an Error in getOctD(x, offset, len) : invalid octal digit

What can cause it?
Thanks!

**Comment by pikapika505** [comment]
Found a solution. Shouldn't use curl to download it

**Comment by GabriellaAraujo** [comment]
How you fixed this problem?
I am having a similar problem and I have tried to fix it but without success.

**Comment by OscarKrijgsman** [comment]
The answer can be found here:
https://stackoverflow.com/questions/18652923/error-in-getoctdx-offset-len-invalid-octal-digit

The tarbal is probably corrupt. Please try to download it and try again.

**Comment by GabriellaAraujo** [comment]
Thanks! :)
