### ISSUE TITLE
'Realloc' could not re-allocate memory

### ISSUE THREAD

**Issue by rgescudero** [PeeperLab/XenofilteR#16]
I'm trying to use Xenofilter for a human cancer cell line xenograft in mouse for the firts time, in my Windows 7 labtop, with R version 4.0.0 (2020-04-24) -- "Arbor Day". 
I got this error, and the bam file generated is not "completed":

**Code:**

`>library(XenofilteR)`

`>path <- dir(system.file(package = "XenofilteR"), "extdata", full.names = TRUE)`

`>bp.param <- SnowParam(workers = 1, type = "SOCK")`

`>samples <- list.files(path = "bam", pattern = ".bam$", full.names = TRUE)`

`>Sample_list <- data.frame(samples[1], samples[2])`

The following samples will be analyzed: 
graft: C:/Users/Administrador/Desktop/bam/1_control_human.bam ; 	 matching host: C:/Users/Administrador/Desktop/bam/1_control_mouse.bam
This analysis will be run on 1 cpus 
[1] "1_control_human.bam  - Filtered 4152703 read pairs out of 16942596  -  24.51 Percent"
**Error in value[[3L]](cond) : 
  'Realloc' could not re-allocate memory (4000000 bytes)
  file: C:/Users/Administrador/Desktop/bam/1_control_human.bam
  index: C:/Users/Administrador/Desktop/bam/1_control_human.bam**

**Some memory info:**
`> memory.limit()`
[1] 8106

`> memory.size()`
[1] 7768.02

`> memory.profile()`
       NULL      symbol    pairlist     closure environment     promise 
          1       28231     3033468       70284       10824       19051 
   language     special     builtin        char     logical     integer 
     839007          45         696       97225      108043      614379 
     double     complex   character         ...         any        list 
      35954          59     1143021           1           0      301529 
 expression    bytecode externalptr     weakref         raw          S4 
          2      276913        4210         858         886        9183

Can you help me fix it? I have got 14 samples more to analyze!!!
Best wihes

Ramon

**Comment by RoelKluin** [comment]
It looks like your laptop has too little ram to keep the reads in memory. Try on a workstation with more ram (best option) or split the fastq before alignments, filter those and combine the filtered files.

Best, Roel

**Comment by rgescudero** [comment]
Thanks Roel,

I'm now using a 32 GB RAM labtop, and it is working perfectly

Best wishes and great software!!!

Ramon
