### ISSUE TITLE
invalid class “PhredQuality” object

### ISSUE THREAD

**Issue by corticaltone** [PeeperLab/XenofilteR#17]
Hi
I'm trying to run XenofilteR on bam files I alligned using rsubread on fastq files generated on a NextSeq 550. I get the folllowing error message:
Error in validObject(.Object) : 
  invalid class “PhredQuality” object: undefined class for slot "elementMetadata" ("DataTable_OR_NULL")

Any idea what I might be doing wrong? Here's my code:
library(XenofilteR)
library(BiocParallel)
reference_folder <- "/omics/odcf/analysis/OE0519_projects/chptumor/references"
fastq_folder <- "/omics/odcf/project/OE0519/chptumor/sequencing/rna_sequencing/view-by-pid/"
destination.folder <- paste0("/icgc/dkfzlsdf/analysis/OE0519_projects/chptumor/CSF/iPSCneuronsCSF/Xenofilter_out")
bp.param <- SnowParam(workers = 7, type = "SOCK")

samples <- c("CSF8", "CSF11", "CSF14", "CSF15", "CSF16", "CSF20")

#Generate sample.list and outputames
output.names <- c("CSF8.bam", "CSF11.bam", "CSF14.bam", "CSF15.bam", "CSF16.bam", "CSF20.bam")
sample_listH <- vector()
sample_listM <- vector()
for (sample in samples) {
  human_path <- paste0("/icgc/dkfzlsdf/analysis/OE0519_projects/chptumor/CSF/CSFAmit1/Human/", sample, "_human.bam")
  sample_listH <- c(sample_listH, human_path)
  mouse_path <- paste0("/icgc/dkfzlsdf/analysis/OE0519_projects/chptumor/CSF/CSFAmit1/Mouse/", sample, "_mouse.bam")
  sample_listM <- c(sample_listM, mouse_path)
  
  
}

#human run
sample.list <- data.frame(sample_listH, sample_listM)
XenofilteR(sample.list = sample.list, destination.folder = destination.folder, bp.param = bp.param, output.names)

**Comment by RoelKluin** [comment]
I cannot reproduce the issue. The PhredQuality are the quality scores in the bam file, the error suggests these are not ok, are these valid bam files? also, what are your R and bioconducter versions?
