### ISSUE TITLE
How to remove human reads from PDX samples aligned to mouse genome ? 

### ISSUE THREAD

**Issue by akramdi** [PeeperLab/XenofilteR#18]
Hello, 

This might not be why xenofilteR is typically used for, but I would like to filter possible contaminating human reads from bam files aligned to the mouse genome. Would this be possible simply by inverting the columns in  `sample.list` matrix ? 
 
First column:  path to bam file names mapped to the mouse genome 
Second column :  path to bam files mapped to the human genome

Thanks for the help.
Best,

**Comment by OscarKrijgsman** [comment]
Hello, 

Thank you for using Xenofilter. 
Yes, this will work. We used it as well that way. 

Kind regards, Oscar

**Comment by akramdi** [comment]
Great, thanks for quick reply ! I'll give it a try.
Best,
