### ISSUE TITLE
BiocParallel errors. Could not find function "FilterRules"

### ISSUE THREAD

**Issue by Cherif-BA** [PeeperLab/XenofilteR#19]
Hi there, 
I am trying to run XenofilteR in R (Ubuntu system) and I'm getting the following error. See below I have copied and pasted the workflow proposed in the vignette.

> library(XenofilteR) 
> path <- dir(system.file(package = "XenofilteR"), "extdata", full.names = TRUE)                                        
> samples <- list.files(path = path, pattern = ".bam$", full.names = TRUE)                                              
> Sample_list <- data.frame(samples[1], samples[2])                                                                     
> Sample_list                                                                                                                                                                                       samples.1.1 /home/cherif/R/x86_64-pc-linux-gnu-library/4.1/XenofilteR/extdata/Test_hg19_NRAS.bam                                                                                                              samples.2. 1 /home/cherif/R/x86_64-pc-linux-gnu-library/4.1/XenofilteR/extdata/Test_mm10_NRAS.bam                                  > bp.param <- SnowParam(workers = 8, type = "SOCK")                                                                     
> bp.param                                                                                                              
class: SnowParam                                                                                                         
 bpisup: FALSE; bpnworkers: 8; bptasks: 0; bpjobname: BPJOB                                                             
 bplog: FALSE; bpthreshold: INFO; bpstopOnError: TRUE                                                                   
 bpRNGseed: ; bptimeout: 2592000; bpprogressbar: FALSE                                                                   
bpexportglobals: TRUE; bpforceGC: FALSE                                                                                 
bplogdir: NA                                                                                                            
bpresultdir: NA                                                                                                         
cluster type: SOCK                                                                                                    
> XenofilteR(Sample_list, destination.folder = "./", bp.param = bp.param, output.names = NULL )                                                                                                                     The following samples will be analyzed:                                                                                 
graft: /home/cherif/R/x86_64-pc-linux-gnu-library/4.1/XenofilteR/extdata/Test_hg19_NRAS.bam ;    
matching host: /home/cherif/R/x86_64-pc-linux-gnu-library/4.1/XenofilteR/extdata/Test_mm10_NRAS.bam                                            This analysis will be run on 8 cpus                                                                                     
Finished calculating which reads can be assigned to human - Start writing filtered Bam files                                                                                                                                                    Error: BiocParallel errors                                                                                                
1 remote errors, element index: 1                                                                                       
0 unevaluated and other errors                                                                                         
 first remote error: could not find function "FilterRules"                                                             
> Warning messages:                                                                                                     
1: In (function (fmt, ...)  :                                                                                             
2 arguments not used by format 'Finished reading human sample'                                                        
2: In (function (fmt, ...)  :                                                                                             
3 arguments not used by format 'Finished reading mouse sample'  

Have anyone encountered the same issue before? I have reinstalled all the dependencies but am still, having the same problem. Any fixes? 
Thanks in advance for your reply.
Cherif

**Comment by Cherif-BA** [comment]
Hi,

Just came up with some updates on this. I have been able to bypass this issue by simply requiring the package "S4Vectors". Maybe it can be added to the XenofilteR package. 

Many thanks for the package. It's working great now.

BW,

Cherif

**Comment by RoelKluin** [comment]
This is related to issue #7, the issue is with RSamtools, which cannot be fixed here.
