### ISSUE TITLE
The Reads should be filtered?

### ISSUE THREAD

**Issue by YingYa** [PeeperLab/XenofilteR#2]
Hi,

For the large memory be required by directly using XenofilteR, I rewrite the pipeline by Perl, Samtools and Picard to reduce memory usage. I filtered more reads than XenofilteR do on test data (inst/extdata), but the reads I think should be filtered. Here is the Map_info of the reads just kept by XenofilteR:
HS25_11846:8:1306:9325:20892#2  52      8       9       7
HS20_11786:8:1107:12033:7573#2  58      8       0       17
HS20_11786:8:1210:3798:76508#2  58      8       0       17
HS20_11786:8:1211:2994:4840#2   58      8       0       17
HS20_11786:8:2203:11794:38178#2 58      8       0       17

Then I ran the command of R/XenofilteR.R row by row, and I got the same result with  the pipeline wrote by Perl.

What may be the problem?

Thanks,
Ya

**Comment by RoelKluin** [comment]
Too late probably, but I cannot tell without the commandline. In the `original' branch (git) you'll find a perl version, though it may lack some changes.
