### ISSUE TITLE
Recommended parameters for 110 bp paired-reads

### ISSUE THREAD

**Issue by ZReplicant** [PeeperLab/XenofilteR#25]
Hello!

Thanks for developing this tool. I tried running XenofilteR, and it worked without any issues. However, I used the basic command mentioned in the readme:
`XenofilteR(sample.list, destination.folder = in_path, bp.param = bp.param, output.names)`
Even though my reads are 110 bp (paired-end, RNA-seq DEG-analysis experiment).

I thought I could change the parameters like it was written in the readme. Would you please recommend the values for `MM_threshold` and `Unmapped_penalty` as I was not able to google any clues?

Thank you.

**Comment by RoelKluin** [comment]
Dear Zhanna,

For pe 110bp I'd recommend paired-end adapter trimming beforehand, and
maybe quality trimming, if e.g. fastqc shows quality declines with length.
Tools: Seqpurge, or cutadapt if quality trimming is required. Soft-clipped
bases are counted as mismatches. Thresholds should still be ok. You could
elevate the mismatch threshold and unmapped penalty to 8 and 12, or disable
the first by setting it to readlength.

Best regards, Roel

**Comment by ZReplicant** [comment]
Dear Roel,

Thank you very much for the fast answer.
I did perform adapter and quality trimming beforehand. Then, I will probably stick with the default parameters. Will raising the mismatch threshold and unmapped penalty to 8 and 12 improve specificity in my case?

Best regards,
Zhanna

**Comment by RoelKluin** [comment]
I'd say raising thresholds can increase sensitivity, but specificity can only decrease.

**Comment by ZReplicant** [comment]
Ok, thank you again. Your answers really helped!
