### ISSUE TITLE
Effect of reference genome version

### ISSUE THREAD

**Issue by smsamin** [PeeperLab/XenofilteR#27]
Hi, I was wondering to ask if reference genome utilized for alignment would have any impact on filteration of contaminated reads? I am using the latest T2T-CHM13v2.0 human and mouse mm39 assemblies from UCSC for the alignment. 
Thanks!

**Comment by RoelKluin** [comment]
The reference genome you use will have an impact, but the closer the reference genome matches your sample, the better the filtering will work. The filtering is based on edit distance. If you think your cells might have deviated from the reference, I'd suggest increasing the mismatch threshold. If the host is not C57BL/6, and you have a better reference genome for the mouse then it is better to adapt that as well.
