### ISSUE TITLE
Any update soon?

### ISSUE THREAD

**Issue by tizilys** [PeeperLab/XenofilteR#28]
Hello,

I have some problems with the installation of the XenofilteR package, as it has legacy requirements which are not compatible with our HPC system… so I just would like to ask you if you are planning to release an update of the application and its requirements anytime soon, or whether it would be possible to do it… 

Thanks in advance for your answer! :)

**Comment by RoelKluin** [comment]
I'm still using the package and it works for me. My R may not be latest
though. What error exactly are you having? If this is about S3 vectors or
so, then I think there is already an issue that handles it.
