### ISSUE TITLE
Mouse-read output option not implemented

### ISSUE THREAD

**Issue by JohnMCMa** [PeeperLab/XenofilteR#3]
The XenofilteR paper states, "[d]efault output of XenofilteR is a new bam file with the sequence reads classified as human. Optionally, a second bam file can be generated with the sequence reads classified as mouse."

However, from what I see in the code and from the man pages, the module can't output mouse-filtered reads. Is there a reason it wasn't implemented?

**Comment by PeeperLab2** [comment]
Dear John Ma,

Thank you for using XenofilteR.
You are completely right. What is written in the manuscript and available in XenofilteR does not 100% match at the moment. I am working on a new version in which this will implemented but it slows down XenofilteR, even when only exporting the human filtered data. Therefore, I still prefer the version that exports 1 bam file per sample only.

For those who are interested in the mouse reads, there is a very simple solution which I have also used for my papers. You can swap the mouse and human data when running XenofilteR, this way the filtered mouse reads will be exported.

I hope this will work for you. If not let me know and I will provide a version for your needs asap.

Kind regards, Oscar

Oscar Krijgsman, PhD
Postdoctoral research fellow
Division of Molecular Oncology & Immunology
The Netherlands Cancer Institute
Plesmanlaan 121
1066 CX Amsterdam, the Netherlands
Phone:  +31 20 512 2028
o.krijgsman@nki.nl<mailto:o.krijgsman@nki.nl>


On 21 Feb 2019, at 23:03, John Ma <notifications@github.com<mailto:notifications@github.com>> wrote:


The XenofilteR paper states, "[d]efault output of XenofilteR is a new bam file with the sequence reads classified as human. Optionally, a second bam file can be generated with the sequence reads classified as mouse."

However, from what I see in the code and from the man pages, the module can't output mouse-filtered reads. Is there a reason it wasn't implemented?

**Comment by JohnMCMa** [comment]
Thanks for @PeeperLab 's quick response. Yes, currently I am doing it both ways to obtain both graft and host alignments; although thanks for the the confirmation that the filters are indeed symmetrically applied.

Best regards,
John Ma, PhD
