### ISSUE TITLE
XenofilteR is filtering out all the reads

### ISSUE THREAD

**Issue by raunimarques** [PeeperLab/XenofilteR#30]
Hello, I'm trying to use the XenofilteR package, but the algorithm is removing all the reads from the BAM file. I mapped the FASTQ files to the human and mouse genomes separately. However, the result I receive is that 100% of the reads were filtered. What could be causing this error?

I also generated the .bai files for each BAM file.

![Captura de tela de 2024-09-14 17-00-17](https://github.com/user-attachments/assets/67cee61e-0aab-4c59-9b15-52a7f27cea42)

**Comment by RoelKluin** [comment]
Possibilities are that files did not match or the read names did not correspond.
