### ISSUE TITLE
Problem to implement and use function "FilterRules"

### ISSUE THREAD

**Issue by rekren** [PeeperLab/XenofilteR#5]
Hello,
Thanks for coming up with such nice package to filter out host reads from PDX data.
I am running XenofilteR on R version 3.5.1 (2018-07-02) -- "Feather Spray" in Windows 10 OS.
When I try to run following code, I took error about "FilterRules" function.

` XenofilteR(sample.list = sample.list, destination.folder = "D:/work/raw/mapped/xeno", bp.param = bp.param, output.names = NULL)`

> The following samples will be analyzed: 
> graft: D:/work/raw/mapped/hs_nm5_1_clean_Aligned.sortedByCoord.out.bam ; 	 matching host: D:/work/raw/mapped/mm_nm5_1_clean_Aligned.sortedByCoord.out.bam
> graft: D:/work/raw/mapped/hs_nm5_2_clean_Aligned.sortedByCoord.out.bam ; 	 matching host: D:/work/raw/mapped/mm_nm5_2_clean_Aligned.sortedByCoord.out.bam
> graft: D:/work/raw/mapped/hs_nm6_1_clean_Aligned.sortedByCoord.out.bam ; 	 matching host: D:/work/raw/mapped/mm_nm6_1_clean_Aligned.sortedByCoord.out.bam
> graft: D:/work/raw/mapped/hs_nm6_2_clean_Aligned.sortedByCoord.out.bam ; 	 matching host: D:/work/raw/mapped/mm_nm6_2_clean_Aligned.sortedByCoord.out.bam
> This analysis will be run on 8 cpus 
> [1] "hs_nm6_1_clean_Aligned.sortedByCoord.out.bam  - Filtered 820329 reads out of 13199896  -  6.21 Percent"
> Error: BiocParallel errors
>   element index: 1
>   first error: could not find function "FilterRules"
> In addition: Warning messages:
> 1: In serialize(data, node$con) :
>   'package:stats' may not be available when loading
> 2: In serialize(data, node$con) :
>   'package:stats' may not be available when loading
> 3: In serialize(data, node$con) :
>   'package:stats' may not be available when loading
> 4: In serialize(data, node$con) :
>   'package:stats' may not be available when loading
> 5: In serialize(data, node$con) :
>   'package:stats' may not be available when loading
> 6: In serialize(data, node$con) :
>   'package:stats' may not be available when loading
> 7: In serialize(data, node$con) :
>   'package:stats' may not be available when loading
> 8: In serialize(data, node$con) :
>   'package:stats' may not be available when loading
> 9: stop worker failed:
>   'clear_cluster' receive data failed:
>   reached elapsed time limit

**Comment by PeeperLab2** [comment]
Hi,

Thank you for using XenofilteR.

XenofilteR v1.5 is developed to work with the latest versions of R and Bioconductor. Packages and function on which XenofilteR depends sometimes change between Bioconductor version. The function FilterRules changed between version. Please update your R and BioC versions or, alternatively, use an earlier version of XenofilteR:
https://github.com/PeeperLab/XenofilteR/releases/tag/V1.4

Please also check if all packages needed by XenofilteR are properly loaded.

Hope this helps, if you still experience problems please let me know and include the XenofilteR log file.

Kind regards, Oscar





On 2 May 2019, at 10:49, rekren <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,
Thanks for coming up with such nice package to filter out host reads.
I am running XenofiltR on R version 3.5.1 (2018-07-02) -- "Feather Spray" in Windows 10 OS.
When I try to run following code, I took error about "FilterRules" function.

XenofilteR(sample.list = sample.list, destination.folder = "D:/work/raw/mapped/xeno", bp.param = bp.param, output.names = NULL)

The following samples will be analyzed:
graft: D:/work/raw/mapped/hs_nm5_1_clean_Aligned.sortedByCoord.out.bam ; matching host: D:/work/raw/mapped/mm_nm5_1_clean_Aligned.sortedByCoord.out.bam
graft: D:/work/raw/mapped/hs_nm5_2_clean_Aligned.sortedByCoord.out.bam ; matching host: D:/work/raw/mapped/mm_nm5_2_clean_Aligned.sortedByCoord.out.bam
graft: D:/work/raw/mapped/hs_nm6_1_clean_Aligned.sortedByCoord.out.bam ; matching host: D:/work/raw/mapped/mm_nm6_1_clean_Aligned.sortedByCoord.out.bam
graft: D:/work/raw/mapped/hs_nm6_2_clean_Aligned.sortedByCoord.out.bam ; matching host: D:/work/raw/mapped/mm_nm6_2_clean_Aligned.sortedByCoord.out.bam
This analysis will be run on 8 cpus
[1] "hs_nm6_1_clean_Aligned.sortedByCoord.out.bam - Filtered 820329 reads out of 13199896 - 6.21 Percent"
Error: BiocParallel errors
element index: 1
first error: could not find function "FilterRules"
In addition: Warning messages:
1: In serialize(data, node$con) :
'package:stats' may not be available when loading
2: In serialize(data, node$con) :
'package:stats' may not be available when loading
3: In serialize(data, node$con) :
'package:stats' may not be available when loading
4: In serialize(data, node$con) :
'package:stats' may not be available when loading
5: In serialize(data, node$con) :
'package:stats' may not be available when loading
6: In serialize(data, node$con) :
'package:stats' may not be available when loading
7: In serialize(data, node$con) :
'package:stats' may not be available when loading
8: In serialize(data, node$con) :
'package:stats' may not be available when loading
9: stop worker failed:
'clear_cluster' receive data failed:
reached elapsed time limit

**Comment by rekren** [comment]
Hello again, thanks for reply.

All installed packages were up-to-date. I was unable to solve the problem properly but, when I run XenofiltR with `bp.param <- SerialParam()`  I was able to by-pass "FilterRules" function. 
BiocParallel might have some conflict on the dependency checks on parallel computing.

Another thing is, after run XenofiltR in paired-end mapped .bam files to filter mouse reads from human mapped reads, obtained filtered .bam files were flagged suspicious on quantification tool Salmon 

>[2019-05-03 13:05:06.362] [jointLog] [warning]                                                                                                                                                                                                                                                                                                                          WARNING: Detected suspicious pair --- 
The names are different:                                                                                                
read1 : A00721:26:HGC2YDSXX:1:1141:20835:24424                                                                         
 read2 : A00721:26:HGC2YDSXX:1:1534:2003:17174                                                                                                                                                                                           [2019-05-03 13:05:06.362] [jointLog] [warning]                                                                                                                                                                                                                                                                                                                          WARNING: Detected suspicious pair ---                                                                                           
The names are different:                                                                                                
read1 : A00721:26:HGC2YDSXX:1:1217:32741:7529                                                                           
read2 : A00721:26:HGC2YDSXX:1:1304:13042:20353                                                                                                                                                                                          [2019-05-03 13:05:06.362] [jointLog] [warning]                                                                                                                                                                                                                                                                                                                          WARNING: Detected suspicious pair ---                                                                                           
The names are different:                                                                                                
read1 : A00721:26:HGC2YDSXX:1:1335:5620:32017                                                                           
read2 : A00721:26:HGC2YDSXX:1:1674:31458:9345  
....
....
....

This log file continues to the size of 8 gigabyte text file.
What disrupts the pair-end .bam files on the filtering process of XenofiltR ?

Thanks in advanced.
Sincerely,
-R

**Comment by PeeperLab2** [comment]
Hi,

Could you please send me the log file? This file contains all the version of all the packages XenofilteR used for the run. With this info I can try to replicate the problem.

I have never seen this issue before. Have you checked the original input file? All reads in this file match properly?
I have no idea what the problem could be without looking at the actual files. Would it be possible to share a minimal set to replicate the error on my machine?

Kind regards, Oscar






On 7 May 2019, at 12:44, rekren <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello again, thanks for reply.

All installed packages were up-to-date. I was unable to solve the problem properly but, when I run XenofiltR with bp.param <- SerialParam() I was able to by-pass "FilterRules" function.
BiocParallel might have some conflict on the dependency checks on parallel computing.

Another thing is, after run XenofiltR in paired-end mapped .bam files to filter mouse reads from human mapped reads, obtained filtered .bam files were flagged suspicious on quantification tool Salmon

[2019-05-03 13:05:06.362] [jointLog] [warning] WARNING: Detected suspicious pair --- The names are different: read1 : A00721:26:HGC2YDSXX:1:1141:20835:24424 read2 : A00721:26:HGC2YDSXX:1:1534:2003:17174 [2019-05-03 13:05:06.362] [jointLog] [warning] WARNING: Detected suspicious pair --- The names are different: read1 : A00721:26:HGC2YDSXX:1:1217:32741:7529 read2 : A00721:26:HGC2YDSXX:1:1304:13042:20353 [2019-05-03 13:05:06.362] [jointLog] [warning] WARNING: Detected suspicious pair --- The names are different: read1 : A00721:26:HGC2YDSXX:1:1335:5620:32017 read2 : A00721:26:HGC2YDSXX:1:1674:31458:9345

What disrupts the pair-end .bam files on the filtering process of XenofiltR ?

Thanks in advanced.
Sincerely,
-R

**Comment by rekren** [comment]
[XenofilteR.log](https://github.com/PeeperLab/XenofilteR/files/3152269/XenofilteR.log)

I have attached the log file of XenofilteR.

Yes previously, I have tested on single-end .bam files with serial run and the Salmon quantification without problem. 
However, I have faced following problem on Salmon quantification tool, after paired-end files were filtered by XenofilteR.

> WARNING: Detected suspicious pair ---
The names are different:
read1 : A00721:26:HGC2YDSXX:1:1335:5620:32017
read2 : A00721:26:HGC2YDSXX:1:1674:31458:9345
.....

**Comment by PeeperLab2** [comment]
Thank you for the log file.
I have been able to reproduce the error. I’ll sort out the FilterRules error first and next look into your second problem with the read names.

I’ll be in touch soon. Best Oscar


On 7 May 2019, at 13:20, rekren <notifications@github.com<mailto:notifications@github.com>> wrote:


XenofilteR.log<https://github.com/PeeperLab/XenofilteR/files/3152269/XenofilteR.log>

I have attached the log file of XenofiltR.

Yes previously, I have tested on single-end .bam files with serial run and the Salmon quantification without problem.
However, I have faced following problem on Salmon quantification tool, after paired-end files were filtered by XenofiltR.

WARNING: Detected suspicious pair ---
The names are different:
read1 : A00721:26:HGC2YDSXX:1:1335:5620:32017
read2 : A00721:26:HGC2YDSXX:1:1674:31458:9345
.....

**Comment by PeeperLab2** [comment]
Hi,

I solved the FilterRules issue. The bioconductor team updated multiple packages and the function FilterRules is now only available in S4vector package.
I am running some additional tests but the new version of XenofilteR should be available on Github tonight under “releases”.

Regarding your second question:
XenofilteR bam output files are sorted in genomic location. I think Salmon expects name sorted bam files. This explains why you did not see the error with SE samples but do see it with PE samples.
Please check the Salmon manual and sort the bam files (samtools sort -n) before the Salmon quantification.

Good luck and let me know if you have any other questions.
Best Oscar





On 7 May 2019, at 13:20, rekren <notifications@github.com<mailto:notifications@github.com>> wrote:


XenofilteR.log<https://github.com/PeeperLab/XenofilteR/files/3152269/XenofilteR.log>

I have attached the log file of XenofiltR.

Yes previously, I have tested on single-end .bam files with serial run and the Salmon quantification without problem.
However, I have faced following problem on Salmon quantification tool, after paired-end files were filtered by XenofiltR.

WARNING: Detected suspicious pair ---
The names are different:
read1 : A00721:26:HGC2YDSXX:1:1335:5620:32017
read2 : A00721:26:HGC2YDSXX:1:1674:31458:9345
.....
