### ISSUE TITLE
Get mouse & human filtered bams simultaneously

### ISSUE THREAD

**Issue by ChelseaCHENX** [PeeperLab/XenofilteR#9]
Hello!
I want to measure the proportion of true mouse & human reads from the xenograft sample - wonder if I can get the bam files from both mouse and human after filtering? Given the input are bam files aligned to human and mouse genome respectively. I wonder if just swapping input order will do the trick? Thanks!

**Comment by PeeperLab2** [comment]
Hello,

Yes, Swapping the input will definitively work!
Good luck! Best Oscar



On 12 Jul 2019, at 16:49, Chelsea Chen <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello!
I want to measure the proportion of true mouse & human reads from the xenograft sample - wonder if I can get the bam files from both mouse and human after filtering? Given the input are bam files aligned to human and mouse genome respectively. I wonder if just swapping input order will do the trick? Thanks!
